### ISSUE TITLE
运行demo时发生错误

### ISSUE THREAD

**Issue by newdimitri** [gongxijun/ocr_recognition#7]
未改动文件直接运行的，看起来像是读取模型时候有错误
```
(mxnet_p27) root@ip-172-31-6-25:~/ocr_recognition-master/recaptcha# python ocr_predict.py
Traceback (most recent call last):
  File "ocr_predict.py", line 29, in <module>
    _, arg_params, __ = mx.model.load_checkpoint('../model/model', iteration)
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/model.py", line 420, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 2518, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op warpctc0 of type WarpCTC: [09:03:29] src/core/op.cc:55: Check failed: op != nullptr Operator WarpCTC is not registered

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x276938) [0x7fea1ed17938]
[bt] (1) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4a25ed5) [0x7fea234c6ed5]
[bt] (2) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4a57c2b) [0x7fea234f8c2b]
[bt] (3) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4a5cf50) [0x7fea234fdf50]
[bt] (4) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4a567ff) [0x7fea234f77ff]
[bt] (5) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x25decdf) [0x7fea2107fcdf]
[bt] (6) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4a291cd) [0x7fea234ca1cd]
[bt] (7) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x25dfe6d) [0x7fea21080e6d]
[bt] (8) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x25decdf) [0x7fea2107fcdf]
[bt] (9) /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x4a291cd) [0x7fea234ca1cd]
```

**Comment by gongxijun** [comment]
The problem may be that you didn't compile the moudle of warpctc .

**Comment by gongxijun** [comment]
@newdimitri The problem may be that you didn't compile the moudle of warpctc .
